import { Networks } from "stellar-sdk";

export const BLEND_CONFIG = {
    POOL_ID: "CCCCIQSDILITHMM7PBSLVDT5MISSY7R26MNZXCX4H7J5JQ5FPIYOGYFS",
    USDC_ASSET_ID: "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75",
    USDC_ISSUER: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
    STELLAR_RPC: "https://horizon.stellar.org",
    SOROBAN_RPC: "/api/proxy-soroban",
    NETWORK_PASSPHRASE: Networks.PUBLIC,
};
